### ISSUE TITLE
Chart series not overriding original one

### ISSUE THREAD

**Issue by marianopeck** [ba-st/HighchartsSt#24]
If I do `chart addSeries arearange` that answers me a good instance of `HighstockSeriesArearange`. However if you inspect the result of `chart series` you will see the instance in there is a `"a HighstockSeries ({""type"":""arearange""})"` instead of a `HighstockSeriesArearange`.

The problem is that the methods like `column`, `line` , etc are NOT replacing the original `HighstockSeries` instance created by `addSeries`. 

My workaround is this:

		series := HighchartsSeries new column.
		chart series add: series.

**Comment by mtabacman** [comment]
The protocol has changed since v12, so this should no longer happen as described. I'll close this and refer anyone interested to check the examples in `HighchartsDemo`
