### ISSUE TITLE
Add Seaside dependency

### ISSUE THREAD

**Issue by mtabacman** [ba-st/HighchartsSt#4]
We should add to the baseline a dependency with the minimum packages from Seaside.

**Comment by gcotelli** [comment]
Closed by #16

**Comment by marianopeck** [comment]
HI @gcotelli 

It a pain to develop and maintain the examples without a proper seaside debugger. I think we should simply change `'Seaside3+JQuery'` `'Seaside3+JQuery+Development'` in the baseline. 

Then, I am not sure if `WADebugErrorHandler` would be the auto-default. If it is, then nothing to do. Else, we can workaround it like this:

     (Smalltalk globals hasClassNamed: #WADebugErrorHandler) ifTrue: [ 
	   	app filter configuration at: #exceptionHandler put: WADebugErrorHandler.
    ]

**Comment by marianopeck** [comment]
Yeah...when Seaside `Development`  group is loaded, you do not even need to set the `WADebugErrorHandler`as it is the default one.
