### ISSUE TITLE
Modify series and yAxis

### ISSUE THREAD

**Issue by mtabacman** [ba-st/HighchartsSt#9]
`series` and `yAxis` by default return a new element the first time, and the same element when called again.
They should be changed to return a collection and never add a new element.
We should also create news methods `addSeries` / `addYAxis` which return a new element, and add them to the collection.

**Comment by marianopeck** [comment]
Hi @mtabacman 

I just realized that the methods `highstockAddSeriesSourceCode` and  `highstockAddYAxisSourceCode` are there in `Highstock6DumpImporter` but I do not see them auto-generated in the highstock package. Could it simply be that you didn't have the time to re-generate and publish a new HighstockV6 package ?

If so, then just please let me know when you were able to commit a new auto-genrated version of HighstockV6. 

Thanks
